### ISSUE TITLE
awa

### ISSUE THREAD

**Issue by apulise** [tacstick/projects#1]
tomen awa

**Comment by tacstick** [comment]
ok

**Comment by apulise** [comment]
tomen awa
**TOMEN AWA**
       _________
      |_-_-_-_-_|
      |_________|
       )_______(
      (_________)
      | M.K.'97 |
      /         \
     /           \
    /             \
   /               \
  /                 \
 /                   \
(_____________________)
 )___________________(
(_____________________)
|                     |
|_____________________|
 )___________________(
|_____________________|
 )___________________(
|                     |
|_____________________|
 )___________________(
|_____________________|
 )___________________(
|                     |
|                     |
|_____________________|
(_____________________)
|_____________________|
(_____________________)
|                     |
|                     |
\_____________________/
 '-------------------'
